### PR TITLE
Add new functionality to readme

### PR DESCRIPTION
**Pull request by dhazelett**
Sorry I spaced it out yesterday 👎

Thanks!

### CODE REVIEW

**Comment by fragkp** [comment]
Thanks for updating the readme :)

I've updated just a couple of minutes before you committed: https://github.com/fragkp/laravel-route-breadcrumb/commit/a5bc4d44d95b1967cd0996dbb3c7e1eeae8f25c3

Could you revert it? After that, i will merge.

**Comment by dhazelett** [comment]
Will do!

Thanks,
Devon Hazelett
Sr. Software Engineer
https://www.motosport.com
https://www.backcountry.com

On Jun 3, 2018, at 02:54, fragkp <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for updating the readme :)

I've updated just a couple of minutes before you committed: a5bc4d4<https://github.com/fragkp/laravel-route-breadcrumb/commit/a5bc4d44d95b1967cd0996dbb3c7e1eeae8f25c3>

Could you revert it? After that, i will merge.

**Comment by dhazelett** [comment]
Sorry for the delay, was busy work stuff. 🍻

**Comment by fragkp** [comment]
Thanks!

**Pull request merged**
